# Generated by Django 4.2.18 on 2025-02-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_injection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sqlinjection',
            table='sqlinjection',
        ),
    ]
